### ISSUE TITLE
Vendor Page - View to the user

### ISSUE THREAD

**Issue by GittBUB** [zednon/Project1#8]
This information will pull from Firebase. The following will be displayed on the page once the user clicks on a vendor option from the User Page.

- [x] Venue name

- [x] Venue address

- [x] Venue capacity

- [x] Description

- [x] Email

- [x] Phone number

- [x] Image

- [ ] Calendar

- [x] Submit button

- [x] Modal upon submit

- [x] User request needs to be saved to Firebase

**Comment by verna100** [comment]
only pending item on this is the image view after upload. the calendar was nixed so nothing to do there.

**Comment by verna100** [comment]
Officially closing this issue as all items have been completed!
